on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Build React app
      run: |
        cd client
        npm run build

    - name: 📂 Compress build files
      run: |
        tar czf build.tar.gz -C client/build .

    - name: 📂 Deploy to cPanel frontend
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server:  ftp.tsidn.org
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        source: build.tar.gz
        target: /home/tsidnorg/infotech.tsidn.org/
    
    